import { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { SEO } from "../components/SEO";

interface Article {
  date: string;
  title: string;
  ingress: string;
  content: string;
}

function formatSwedishDate(dateStr: string): string {
  const parts = dateStr.split("-").map(Number);
  if (parts.length !== 3) return dateStr;
  const [year, month, day] = parts;
  const months = [
    "januari", "februari", "mars", "april", "maj", "juni",
    "juli", "augusti", "september", "oktober", "november", "december",
  ];
  return `${day} ${months[month - 1]} ${year}`;
}

export function NyheterArtikel() {
  const { date } = useParams<{ date: string }>();
  const [article, setArticle] = useState<Article | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    if (!date) {
      setNotFound(true);
      setLoading(false);
      return;
    }
    fetch(`/api/article?date=${date}`)
      .then((r) => {
        if (r.status === 404) {
          setNotFound(true);
          setLoading(false);
          return null;
        }
        if (!r.ok) throw new Error("fetch failed");
        return r.json() as Promise<Article>;
      })
      .then((data) => {
        if (data) setArticle(data);
        setLoading(false);
      })
      .catch(() => {
        setNotFound(true);
        setLoading(false);
      });
  }, [date]);

  if (loading) {
    return (
      <main className="max-w-3xl mx-auto px-4 py-24 flex justify-center">
        <div className="w-8 h-8 border-2 border-indigo-600 border-t-transparent rounded-full animate-spin" />
      </main>
    );
  }

  if (notFound || !article) {
    return (
      <>
        <SEO
          title="Artikel hittades inte | Aikostnad.se"
          description=""
          canonical={`https://aikostnad.se/nyheter/${date ?? ""}`}
        />
        <main className="max-w-3xl mx-auto px-4 py-24 text-center">
          <p className="text-gray-500 mb-4">Artikeln hittades inte.</p>
          <Link
            to="/nyheter"
            className="text-sm text-indigo-600 hover:text-indigo-800 underline"
          >
            ← Alla nyheter
          </Link>
        </main>
      </>
    );
  }

  return (
    <>
      <SEO
        title={`${article.title} | Aikostnad.se`}
        description={article.ingress ?? ""}
        canonical={`https://aikostnad.se/nyheter/${date}`}
      />

      <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <Link
          to="/nyheter"
          className="text-sm text-indigo-600 hover:text-indigo-800 transition-colors mb-8 inline-block"
        >
          ← Alla nyheter
        </Link>

        <article>
          <p className="text-sm text-gray-500 mb-3">
            {formatSwedishDate(article.date)}
          </p>

          <h1 className="text-3xl font-bold text-gray-900 mb-4 leading-tight">
            {article.title}
          </h1>

          {article.ingress && (
            <p className="text-lg text-gray-600 italic border-l-4 border-indigo-300 pl-4 mb-8 leading-relaxed">
              {article.ingress}
            </p>
          )}

          <div
            className="prose max-w-none text-gray-700 mb-12
              prose-headings:text-gray-900 prose-headings:font-semibold
              prose-h2:text-xl prose-h2:mt-8
              prose-p:leading-relaxed
              prose-a:text-indigo-600 prose-a:no-underline hover:prose-a:underline"
            // Article content is generated by our own Claude AI from known RSS sources
            // eslint-disable-next-line react/no-danger
            dangerouslySetInnerHTML={{ __html: article.content }}
          />
        </article>

        <div className="border-t border-gray-200 pt-8 flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between">
          <Link
            to="/nyheter"
            className="text-sm text-gray-500 hover:text-gray-700 transition-colors"
          >
            ← Alla nyheter
          </Link>
          <Link
            to="/token-kalkylator"
            className="inline-block bg-indigo-600 text-white font-semibold px-6 py-3 rounded-lg hover:bg-indigo-700 transition-colors text-sm"
          >
            Räkna ut din AI-kostnad →
          </Link>
        </div>
      </main>
    </>
  );
}
