import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { marked } from "marked";
import { SEO } from "../components/SEO";

interface SavedArticle {
  date: string;
  slug: string;
  title: string;
  ingress: string;
}

function formatSwedishDate(dateStr: string): string {
  const parts = dateStr.split("-").map(Number);
  if (parts.length !== 3) return dateStr;
  const [year, month, day] = parts;
  const months = [
    "januari", "februari", "mars", "april", "maj", "juni",
    "juli", "augusti", "september", "oktober", "november", "december",
  ];
  return `${day} ${months[month - 1]} ${year}`;
}

interface RawArticle {
  title: string;
  link: string;
  pubDate: string;
  summary: string;
  source: string;
}

interface DigestResult {
  title: string;
  ingress: string;
  article: string;
  xPost: string;
  generatedAt: string;
  rawArticles: RawArticle[];
}

function relativeTime(dateStr: string): string {
  if (!dateStr) return "";
  const diff = Date.now() - new Date(dateStr).getTime();
  const minutes = Math.floor(diff / 60_000);
  const hours = Math.floor(diff / 3_600_000);
  const days = Math.floor(diff / 86_400_000);
  if (minutes < 60) return `${minutes} min sedan`;
  if (hours < 24) return `${hours} timm${hours === 1 ? "e" : "ar"} sedan`;
  if (days < 30) return `${days} dag${days === 1 ? "" : "ar"} sedan`;
  return new Date(dateStr).toLocaleDateString("sv-SE", {
    day: "numeric",
    month: "short",
  });
}

function internalLink(title: string): string {
  const t = title.toLowerCase();
  if (t.includes("gpt") || t.includes("openai") || t.includes("chatgpt"))
    return "/vad-kostar-chatgpt";
  if (t.includes("claude") || t.includes("anthropic")) return "/claude-pris";
  if (t.includes("gemini") || t.includes("google")) return "/gemini-pris";
  if (t.includes("deepseek")) return "/deepseek-pris";
  return "/jamfor-ai-modeller";
}

function SourceCard({ article }: { article: RawArticle }) {
  const path = internalLink(article.title);
  return (
    <article className="bg-white border border-gray-200 rounded-lg p-4 hover:border-indigo-200 transition-colors">
      <div className="flex items-center gap-2 text-xs text-gray-500 mb-1.5">
        <span className="font-medium text-indigo-600">{article.source}</span>
        <span>·</span>
        <span>{relativeTime(article.pubDate)}</span>
      </div>
      <h3 className="text-sm font-semibold text-gray-900 leading-snug mb-1.5">
        <a
          href={article.link}
          target="_blank"
          rel="noopener noreferrer"
          className="hover:text-indigo-600 transition-colors"
        >
          {article.title}
        </a>
      </h3>
      {article.summary && (
        <p className="text-xs text-gray-500 leading-relaxed line-clamp-2 mb-2">
          {article.summary}
        </p>
      )}
      <Link
        to={path}
        className="text-xs font-medium text-indigo-600 hover:text-indigo-800 transition-colors"
      >
        Se aktuella priser →
      </Link>
    </article>
  );
}

function DigestView({ digest }: { digest: DigestResult }) {
  const [copied, setCopied] = useState(false);

  const articleHtml =
    digest.article
      ? (marked.parse(digest.article) as string)
      : "";

  const generatedDate = digest.generatedAt
    ? new Date(digest.generatedAt).toLocaleString("sv-SE", {
        day: "numeric",
        month: "long",
        hour: "2-digit",
        minute: "2-digit",
      })
    : "";

  function handleCopy() {
    navigator.clipboard
      .writeText(digest.xPost)
      .then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      })
      .catch(() => {});
  }

  return (
    <section className="bg-white border border-gray-200 rounded-2xl p-6 sm:p-8 mb-10 shadow-sm">
      <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-3 leading-tight">
        {digest.title}
      </h1>

      {digest.ingress && (
        <p className="text-base text-gray-600 italic border-l-4 border-indigo-300 pl-4 mb-6 leading-relaxed">
          {digest.ingress}
        </p>
      )}

      {articleHtml && (
        <div
          className="prose prose-sm sm:prose max-w-none text-gray-700 mb-6
            prose-headings:text-gray-900 prose-headings:font-semibold
            prose-h2:text-lg prose-h3:text-base
            prose-p:leading-relaxed prose-p:text-gray-700
            prose-strong:text-gray-900"
          // Article content is generated by our own Claude AI from known RSS sources
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{ __html: articleHtml }}
        />
      )}

      <div className="flex flex-wrap items-center gap-3 pt-4 border-t border-gray-100">
        {digest.xPost && (
          <button
            onClick={handleCopy}
            className={`text-sm px-4 py-2 rounded-lg border font-medium transition-colors ${
              copied
                ? "border-green-400 text-green-700 bg-green-50"
                : "border-indigo-300 text-indigo-700 bg-indigo-50 hover:bg-indigo-100"
            }`}
          >
            {copied ? "Kopierat! ✓" : "Kopiera X-inlägg"}
          </button>
        )}
        {generatedDate && (
          <span className="text-xs text-gray-400">
            Genererades {generatedDate}
          </span>
        )}
      </div>
    </section>
  );
}

function DigestFallback({ articles }: { articles: RawArticle[] }) {
  return (
    <div className="mb-10">
      <p className="text-sm text-amber-600 bg-amber-50 border border-amber-200 rounded-lg px-4 py-3 mb-6">
        AI-rapporten kunde inte genereras just nu. Här är de senaste nyheterna direkt från källorna.
      </p>
      <div className="space-y-3">
        {articles.map((a, i) => (
          <SourceCard key={`${a.link}-${i}`} article={a} />
        ))}
      </div>
    </div>
  );
}

export function Nyheter() {
  const [digest, setDigest] = useState<DigestResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [savedArticles, setSavedArticles] = useState<SavedArticle[]>([]);

  function fetchDigest() {
    setError(false);
    setLoading(true);
    fetch("/api/daily-digest")
      .then((r) => {
        if (!r.ok) throw new Error("fetch failed");
        return r.json() as Promise<DigestResult>;
      })
      .then((data) => {
        setDigest(data);
        setLoading(false);
      })
      .catch(() => {
        setError(true);
        setLoading(false);
      });
  }

  useEffect(() => {
    fetchDigest();
    fetch("/api/article?list=true")
      .then((r) => (r.ok ? (r.json() as Promise<SavedArticle[]>) : Promise.resolve([])))
      .then((data) => setSavedArticles(Array.isArray(data) ? data : []))
      .catch(() => {});
  }, []);

  const hasDigest = digest && digest.article;
  const rawArticles = digest?.rawArticles ?? [];

  return (
    <>
      <SEO
        title="Dagens AI-rapport | Aikostnad.se"
        description="Daglig AI-nyhetsrapport — det viktigaste inom AI sammanfattat på svenska av aikostnad.se."
        canonical="https://aikostnad.se/nyheter"
      />

      <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {loading && (
          <div className="flex flex-col items-center py-24 gap-4">
            <div className="w-8 h-8 border-2 border-indigo-600 border-t-transparent rounded-full animate-spin" />
            <p className="text-sm text-gray-500">
              Sammanställer dagens AI-rapport…
            </p>
          </div>
        )}

        {!loading && error && (
          <div className="text-center py-20">
            <p className="text-gray-500 mb-4">
              Kunde inte hämta nyheter just nu.
            </p>
            <button
              onClick={fetchDigest}
              className="text-sm text-indigo-600 hover:text-indigo-800 underline"
            >
              Försök igen
            </button>
          </div>
        )}

        {!loading && !error && digest && (
          <>
            {hasDigest ? (
              <DigestView digest={digest} />
            ) : (
              <DigestFallback articles={rawArticles} />
            )}

            {hasDigest && rawArticles.length > 0 && (
              <section>
                <h2 className="text-lg font-semibold text-gray-900 mb-4">
                  Källnyheter
                </h2>
                <div className="space-y-3">
                  {rawArticles.map((a, i) => (
                    <SourceCard key={`${a.link}-${i}`} article={a} />
                  ))}
                </div>
              </section>
            )}
          </>
        )}

        {savedArticles.length > 0 && (
          <section className="mt-12">
            <h2 className="text-lg font-semibold text-gray-900 mb-4">
              Tidigare rapporter
            </h2>
            <div className="space-y-3">
              {savedArticles.map((a) => (
                <Link
                  key={a.date}
                  to={`/nyheter/${a.date}`}
                  className="block bg-white border border-gray-200 rounded-xl p-5 hover:border-indigo-200 transition-colors group"
                >
                  <p className="text-xs text-gray-400 mb-1">
                    {formatSwedishDate(a.date)}
                  </p>
                  <h3 className="text-base font-semibold text-gray-900 group-hover:text-indigo-700 transition-colors leading-snug mb-1">
                    {a.title}
                  </h3>
                  {a.ingress && (
                    <p className="text-sm text-gray-500 line-clamp-2 leading-relaxed">
                      {a.ingress}
                    </p>
                  )}
                </Link>
              ))}
            </div>
          </section>
        )}
      </main>
    </>
  );
}
